FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/
# アプリケーションは `apps` ディレクトリ配下に作りたかったので、追加
RUN mkdir apps
WORKDIR apps
