FROM mysql:latest
# locales をインストールする
RUN apt-get clean && apt-get update && apt-get install -y locales locales-all
# locale 定義ファイルをコンパイルする
RUN locale-gen ja_JP.UTF-8
# 日本語を設定する TODO: もしかして LANG だけでいいのかも...?
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:en
ENV LC_ALL ja_JP.UTF-8
# タイムゾーンに日本を設定する
RUN ln -sf /usr/share/zoneinfo/Japan /etc/localtime
