FROM mysql:5.7.12
# `5.7.12` は自分の使いたいイメージのタグ
RUN apt-get clean && apt-get update && apt-get install -y locales locales-all vim
# ↑のイメージそのままだと vi も vim も入っていなくて不便だったので vim も入れておく
RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:en
ENV LC_ALL ja_JP.UTF-8
RUN ln -sf /usr/share/zoneinfo/Japan /etc/localtime
