version: '3'

services:
  db:
    container_name: mmm_db
    build:
      context: .
      dockerfile: Dockerfile-mysql
    # 文字コードの設定をしておく
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: mmm
      MYSQL_DATABASE: mmm
      MYSQL_USER: mmm
      MYSQL_PASSWORD: mmm
    ports:
      - "3306:3306"  # 大事。ここを書いておかないと、 compose の外から繋げない。

volumes:
  db-data:
